CDB.WebApi/Controllers/CompaniesController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using CDB.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class CompaniesController : BaseController<CompaniesController>
    { 
        private readonly ICompanyService _companyService;

        public CompaniesController(
            ICompanyService companyService,
            IBaseService baseService,
            ILogger<CompaniesController> logger): base(logger, baseService)
        {
            _companyService = companyService;
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> View (int id, CancellationToken ct)
        {
            CompanyDto companyDto = await _companyService.GetCompanyAsync(id, ct);

            if (companyDto == null)
                return View("Error");

            return View(companyDto);
        }



        [AllowAnonymous]
        [HttpGet]
        public ActionResult Create(bool? saved)
        {
            if (saved.HasValue && saved.Value)
                ViewBag.Message = "Saved Successfully";

            CreateCompanyDto createCompanyDto = new CreateCompanyDto();
            ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
            //createCompanyDto.Banks = new SelectList(Enums.Banks, "Id", "DisplayText");

            return View(createCompanyDto);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Create(CreateCompanyDto companyDto, CancellationToken ct)
        {
            int companyId = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    companyId = await _companyService.CreateAsync(companyDto, ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                }
                return RedirectToAction("Edit",  new { id = companyId, created = true });
            }
            else
            {
                return View(companyDto);
            }
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Index(CancellationToken ct)
        {
            List<CompanyDto> result = new List<CompanyDto>();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetAllAsync(ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Edit(int id, CancellationToken ct, bool? saved = null, bool? created = null)
        {
            if (saved.HasValue && saved.Value)
                 ViewBag.Message = "Saved Successfully";
            else if (created.HasValue && created.Value)
                ViewBag.Message = "Created Successfully";

            CompanyDto result = new CompanyDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetCompanyAsync(id, ct);
                    ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Edit(CompanyDto company, CancellationToken ct)
        {
            int? result = null;

            if (ModelState.IsValid)
            {
                result = await _companyService.UpdateCompanyAsync(company, ct);
            }

            if (result.HasValue && result.Value >= 0)
                return RedirectToAction("Edit", new { id = company.Id, saved = true });
            else
                return View();
        }
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
               
            }
            CreateCompanyDto company = new CreateCompanyDto();
            if (company == null)
            {
                
            }
            return View(company);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreateCompanyDto company = new CreateCompanyDto();
            ViewBag.Remove(id);
            ViewBag.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

CDB.WebApi/Controllers/DocumentsController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class DocumentsController : BaseController<DocumentsController>
    {
        private readonly IDocumentService _documentService;

        public DocumentsController(
            IDocumentService documentService,
            IBaseService baseService,
            ILogger<DocumentsController> logger) : base(logger, baseService)
        {
            _documentService = documentService;
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> ListDocuments(int companyId, CancellationToken ct)
        {
            List<DocumentDto> result = new List<DocumentDto>();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _documentService.GetDocumentForCompanyAsync(companyId, ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return PartialView("_ListDocuments", result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> UpdateDocumentPaneAsync(int id, CancellationToken ct)
        {
            DocumentPaneDto result = new DocumentPaneDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result.CompanyId = id;
                    result.Documents = await _documentService.GetDocumentForCompanyAsync(id, ct);
                    //result = await _documentService.GetDocuemntPaneAsync(id, ct);
                    //ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    //ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    //ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> UploadDocument(IFormFile file)
        {
            long size = file.Length;

            // full path to file in temp location
            var filePath = Path.GetTempFileName();
            //byte[] fileBytes = new byte[];
            if (file.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    await _documentService.UploadFile(fileBytes, new CancellationToken());
                    return  RedirectToAction("UpdateDocumentPaneAsync", new { id = 1, ct = new CancellationToken() });
                }
                /* using (var stream = new FileStream(filePath, FileMode.Create))
                 {
                     await file.CopyToAsync(stream);
                 }
             }*/

                
            }
            return Ok();
        }
    }
}

CDB.WebApi/Controllers/ShareholdersController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using CDB.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class ShareholdersController : BaseController<ShareholdersController>
    { 
        private readonly IShareholderService _shareholderService;

        public ShareholdersController(
            IShareholderService shareholderService,
            IBaseService baseService,
            ILogger<ShareholdersController> logger): base(logger, baseService)
        {
            _shareholderService = shareholderService;
        }

        
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Index(int id, CancellationToken ct)
        {
            PaneShareholderDto model = new PaneShareholderDto();

            model.CompanyId = id;
            model.Shareholders = await _shareholderService.GetAllByCompanyAsync(id, ct);
            
            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Create(int companyId, CancellationToken ct)
        {
            ShareholderDto model = new ShareholderDto() { CompanyId = companyId };
            ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
            ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
            ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Create(ShareholderDto model, CancellationToken ct)
        {
            int? result = null;
            if (ModelState.IsValid)
            {
                result = await _shareholderService.UpdateShareholderAsync(model, ct);
            }

            if (result.HasValue && result.Value > 0)
                return RedirectToAction("Edit", new { id = model.Id, saved = true });
            else
                return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Edit(int id, CancellationToken ct, bool? saved)
        {
            ShareholderDto shareHolder = await _shareholderService.GetShareholderByIdAsync(id, ct);

            if (shareHolder == null)
                return View("Error");

            return View(shareHolder);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Edit(ShareholderDto model, CancellationToken ct)
        {
            int? result = null;
            if (ModelState.IsValid)
            {
               result = await _shareholderService.UpdateShareholderAsync(model, ct);
            }

            if (result.HasValue && result.Value > 0)
                return RedirectToAction("Edit", new { id = model.Id, saved = true });
            else
                return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> View(int id, CancellationToken ct)
        {
            ShareholderDto shareHolder = await _shareholderService.GetShareholderByIdAsync(id, ct);

            if (shareHolder == null)
                return View("Error");

            return View(shareHolder);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreateCompanyDto company = new CreateCompanyDto();
            ViewBag.Remove(id);
            ViewBag.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CDB.WebApi/Views/Shareholders/Create.cshtml
@model CDB.BLL.Dto.Request.ShareholderDto

@{
    ViewData["Title"] = "Create";
}
<h4>Add new shareholder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
            @*<div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <input asp-for="CompanyId" class="form-control" />
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShareContribution" class="control-label"></label>
                <input asp-for="ShareContribution" class="form-control" />
                <span asp-validation-for="ShareContribution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinancialNumber" class="control-label"></label>
                <input asp-for="FinancialNumber" class="form-control" />
                <span asp-validation-for="FinancialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceAndDateOfBirth" class="control-label"></label>
                <input asp-for="PlaceAndDateOfBirth" class="form-control" />
                <span asp-validation-for="PlaceAndDateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProcuratorName" class="control-label"></label>
                <input asp-for="ProcuratorName" class="form-control" />
                <span asp-validation-for="ProcuratorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="SigningPersonally" /> @Html.DisplayNameFor(model => model.SigningPersonally)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="SigningThrough" /> @Html.DisplayNameFor(model => model.SigningThrough)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="ShareHolderIdAttached" /> @Html.DisplayNameFor(model => model.ShareHolderIdAttached)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="ProcurationAttached" /> @Html.DisplayNameFor(model => model.ProcurationAttached)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Address.District" class="control-label"></label>
                @Html.DropDownListFor(model => model.Address.District, (SelectList)ViewBag.Districts, new { @class = "form -control" })
                <span asp-validation-for="Address.District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Kaza" class="control-label"></label>
                @Html.DropDownListFor(model => model.Address.Kaza, (SelectList)ViewBag.Kazas, new { @class = "form -control" })
                <span asp-validation-for="Address.Kaza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Road" class="control-label"></label>
                <input asp-for="Address.Road" class="form-control" />
                <span asp-validation-for="Address.Road" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Building" class="control-label"></label>
                <input asp-for="Address.Building" class="form-control" />
                <span asp-validation-for="Address.Building" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Floor" class="control-label"></label>
                <input asp-for="Address.Floor" class="form-control" />
                <span asp-validation-for="Address.Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.CompanyId">Back to List</a>
</div>

CDB.WebApi/Views/Shareholders/Edit.cshtml
@model CDB.BLL.Dto.Request.ShareholderDto

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Shareholder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShareContribution" class="control-label"></label>
                <input asp-for="ShareContribution" class="form-control" />
                <span asp-validation-for="ShareContribution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinancialNumber" class="control-label"></label>
                <input asp-for="FinancialNumber" class="form-control" />
                <span asp-validation-for="FinancialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceAndDateOfBirth" class="control-label"></label>
                <input asp-for="PlaceAndDateOfBirth" class="form-control" />
                <span asp-validation-for="PlaceAndDateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProcuratorName" class="control-label"></label>
                <input asp-for="ProcuratorName" class="form-control" />
                <span asp-validation-for="ProcuratorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="SigningPersonally" /> @Html.DisplayNameFor(model => model.SigningPersonally)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="SigningThrough" /> @Html.DisplayNameFor(model => model.SigningThrough)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="ShareHolderIdAttached" /> @Html.DisplayNameFor(model => model.ShareHolderIdAttached)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="ProcurationAttached" /> @Html.DisplayNameFor(model => model.ProcurationAttached)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Address.District" class="control-label"></label>
                <input asp-for="Address.District" class="form-control" />
                <span asp-validation-for="Address.District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Kaza" class="control-label"></label>
                <select asp-for="Address.Kaza"  asp-items="@ViewBag.Kaza" class="form-control" >
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="Address.Kaza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Road" class="control-label"></label>
                <input asp-for="Address.Road" class="form-control" />
                <span asp-validation-for="Address.Road" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Building" class="control-label"></label>
                <input asp-for="Address.Building" class="form-control" />
                <span asp-validation-for="Address.Building" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Floor" class="control-label"></label>
                <input asp-for="Address.Floor" class="form-control" />
                <span asp-validation-for="Address.Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CDB.WebApi/Views/Shareholders/Index.cshtml
@using CDB.Common;

@model CDB.BLL.Dto.Request.PaneShareholderDto

@{
    ViewData["Title"] = "Shareholders/Index";
}
@Html.HiddenFor(model => model.CompanyId)

<form asp-action="Index">

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Companies" asp-action="Edit" asp-route-id="@Model.CompanyId">Company</a></li>
            <li class="disabled" style="background-color:#d9edf7"><a asp-area="" asp-controller="Shareholders" asp-action="Index" asp-route-id="@Model.CompanyId">Shareholders</a></li>
            <li><a asp-area="" asp-controller="Documents" asp-action="UpdateDocumentPaneAsync" asp-route-id="@Model.CompanyId">Documents</a></li>
        </ul>
    </div>

    <p>
        <a asp-action="Create" asp-route-companyId ="@Model.CompanyId">Create New</a>
    </p>

    @if (Model.Shareholders != null && Model.Shareholders.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Shareholders[0].FullName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Shareholders[0].PhoneNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Shareholders[0].PlaceAndDateOfBirth)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Shareholders[0].ShareContribution)
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Shareholders)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlaceAndDateOfBirth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ShareContribution)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Shareholders", new { id = item.Id }) |
                            @Html.ActionLink("Details", "View", "Shareholders", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", "Shareholders", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }



</form>


<!-- YAMLI CODE START -->
<script type="text/javascript" src="https://api.yamli.com/js/yamli_api.js"></script>
<script type="text/javascript">
    if (typeof (Yamli) == "object" && Yamli.init({ uiLanguage: "en", startMode: "onOrUserDefault" })) {
        Yamli.yamlify("", { settingsPlacement: "bottomLeft" });
        Yamli.yamlify('ArabicCompanyName');
        Yamli.yamlify('FinancialAuditorName');
        Yamli.yamlify('ShareHoldersName');
        Yamli.yamlify('ShareHoldersPosition');
        Yamli.yamlify('RegistPlaceNumb');
        Yamli.yamlify('AuthorizedSignature');
        Yamli.yamlify('LawyerName');

    }
</script>
<!-- YAMLI CODE END -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CDB.WebApi/Views/Shareholders/View.cshtml
@model CDB.BLL.Dto.Request.ShareholderDto

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<div>
    <h4>ShareholderDto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShareContribution)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShareContribution)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FinancialNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FinancialNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlaceAndDateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlaceAndDateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProcuratorName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProcuratorName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SigningPersonally)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SigningPersonally)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SigningThrough)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SigningThrough)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShareHolderIdAttached)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShareHolderIdAttached)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProcurationAttached)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProcurationAttached)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.District)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.District)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Kaza)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Kaza)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Road)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Road)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Building)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Building)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Floor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Floor)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-area="" asp-controller="Shareholders" asp-action="Index" asp-route-id="@Model.CompanyId">Back to List</a>
</div>