CDB.WebApi/Controllers/CompaniesController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using CDB.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class CompaniesController : BaseController<CompaniesController>
    { 
        private readonly ICompanyService _companyService;

        public CompaniesController(
            ICompanyService companyService,
            IBaseService baseService,
            ILogger<CompaniesController> logger): base(logger, baseService)
        {
            _companyService = companyService;
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> View (int id, CancellationToken ct)
        {
            CompanyDto companyDto = await _companyService.GetCompanyAsync(id, ct);

            if (companyDto == null)
                return View("Error");

            return View(companyDto);
        }



        [AllowAnonymous]
        [HttpGet]
        public ActionResult Create(bool? saved)
        {
            if (saved.HasValue && saved.Value)
                ViewBag.Message = "Saved Successfully";

            CreateCompanyDto createCompanyDto = new CreateCompanyDto();
            ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
            //createCompanyDto.Banks = new SelectList(Enums.Banks, "Id", "DisplayText");

            return View(createCompanyDto);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Create(CreateCompanyDto companyDto, CancellationToken ct)
        {
            int companyId = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    companyId = await _companyService.CreateAsync(companyDto, ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                }
                return RedirectToAction("Edit",  new { id = companyId, created = true });
            }
            else
            {
                return View(companyDto);
            }
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Index(CancellationToken ct)
        {
            List<CompanyDto> result = new List<CompanyDto>();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetAllAsync(ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Edit(int id, CancellationToken ct, bool? saved = null, bool? created = null)
        {
            if (saved.HasValue && saved.Value)
                 ViewBag.Message = "Saved Successfully";
            else if (created.HasValue && created.Value)
                ViewBag.Message = "Created Successfully";

            CompanyDto result = new CompanyDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetCompanyAsync(id, ct);
                    ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Edit(CompanyDto company, CancellationToken ct)
        {
            int? result = null;

            if (ModelState.IsValid)
            {
                result = await _companyService.UpdateCompanyAsync(company, ct);
            }

            if (result.HasValue && result.Value >= 0)
                return RedirectToAction("Edit", new { id = company.Id, saved = true });
            else
                return View();
        }
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
               
            }
            CreateCompanyDto company = new CreateCompanyDto();
            if (company == null)
            {
                
            }
            return View(company);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreateCompanyDto company = new CreateCompanyDto();
            ViewBag.Remove(id);
            ViewBag.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

CDB.WebApi/Controllers/CompanyController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using CDB.BLL.Dto.Response;
using CDB.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class CompanyController : BaseController<CompanyController>
    { 
        private readonly ICompanyService _companyService;

        public CompanyController(
            ICompanyService companyService,
            IBaseService baseService,
            ILogger<CompanyController> logger): base(logger, baseService)
        {
            _companyService = companyService;
        }


        [AllowAnonymous]
        [HttpGet]
        public ActionResult CreateAsync(bool? saved)
        {
            if (saved.HasValue && saved.Value)
                ViewBag.Message = "Saved Successfully";

            CreateCompanyDto createCompanyDto = new CreateCompanyDto();
            ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
            //createCompanyDto.Banks = new SelectList(Enums.Banks, "Id", "DisplayText");

            return View(createCompanyDto);
        }


        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> CreateAsync(CreateCompanyDto companyDto, CancellationToken ct)
        {
            int companyId = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    companyId = await _companyService.CreateAsync(companyDto, ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                }
                return RedirectToAction("UpdateCompanyPaneAsync",  new { id = companyId, saved = true });
            }
            else
            {
                return View(companyDto);
            }
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Index(CancellationToken ct)
        {
            List<CompanyDto> result = new List<CompanyDto>();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetAllAsync(ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> UpdateCompanyPaneAsync(int id, CancellationToken ct,bool? saved)
        {
             if (saved.HasValue && saved.Value)
                 ViewBag.Message = "Saved Successfully";

            CompanyPaneDto result = new CompanyPaneDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetCompanyPaneAsync(id, ct);
                    ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> UpdateShareholderPaneAsync(int id, CancellationToken ct)
        {
            ShareholderPaneDto result = new ShareholderPaneDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetShareholderPaneAsync(id, ct);
                    ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> UpdateDocumentPaneAsync(int id, CancellationToken ct)
        {
            CompanyPaneDto result = new CompanyPaneDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _companyService.GetCompanyPaneAsync(id, ct);
                    ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

    }
}

CDB.WebApi/Controllers/DocumentsController.cs
using CDB.BLL.Abstraction;
using CDB.BLL.Dto.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace CDB.WebApi.Controllers
{
    [Route("[controller]/[action]")]
    public class DocumentsController : BaseController<DocumentsController>
    {
        private readonly IDocumentService _documentService;

        public DocumentsController(
            IDocumentService documentService,
            IBaseService baseService,
            ILogger<DocumentsController> logger) : base(logger, baseService)
        {
            _documentService = documentService;
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> ListDocuments(int companyId, CancellationToken ct)
        {
            List<DocumentDto> result = new List<DocumentDto>();
            if (ModelState.IsValid)
            {
                try
                {
                    result = await _documentService.GetDocumentForCompanyAsync(companyId, ct);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return PartialView("_ListDocuments", result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> UpdateDocumentPaneAsync(int id, CancellationToken ct)
        {
            DocumentPaneDto result = new DocumentPaneDto();
            if (ModelState.IsValid)
            {
                try
                {
                    result.CompanyId = id;
                    result.Documents = await _documentService.GetDocumentForCompanyAsync(id, ct);
                    //result = await _documentService.GetDocuemntPaneAsync(id, ct);
                    //ViewBag.CompanyTypes = new SelectList(Enums.CompanyTypes, "Id", "DisplayText");
                    //ViewBag.Districts = new SelectList(Enums.Governates, "Id", "DisplayText");
                    //ViewBag.Kazas = new SelectList(Enums.Kazas, "Id", "DisplayText");
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message);
                    throw (e);
                }
            }
            return View(result);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> UploadDocument(IFormFile file)
        {
            long size = file.Length;

            // full path to file in temp location
            var filePath = Path.GetTempFileName();
            //byte[] fileBytes = new byte[];
            if (file.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    await _documentService.UploadFile(fileBytes, new CancellationToken());
                    return  RedirectToAction("UpdateDocumentPaneAsync", new { id = 1, ct = new CancellationToken() });
                }
                /* using (var stream = new FileStream(filePath, FileMode.Create))
                 {
                     await file.CopyToAsync(stream);
                 }
             }*/

                
            }
            return Ok();
        }
    }
}

CDB.WebApi/Views/Companies/Edit.cshtml
@model CDB.BLL.Dto.Request.CompanyDto

@{
    ViewData["Title"] = "UpdateCompanyPaneAsyncy";
}

@{ if (@ViewBag.Message != null)
    {
    <div class="successmessage" style="text-align:center;color:green">
        <h2><span>@ViewBag.Message</span></h2>
    </div>
        }
    }

<form asp-action="Edit">

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class="disabled" style="background-color:#d9edf7"><a asp-area="" asp-controller="Companies" asp-action="Edit" asp-route-id="@Model.CompanyId">Company</a></li>
            <li><a asp-area="" asp-controller="Shareholders" asp-action="Index" asp-route-id="@Model.Id">Shareholders</a></li>
            <li><a asp-area="" asp-controller="Documents" asp-action="UpdateDocumentPaneAsync" asp-route-id="@Model.Id">Documents</a></li>
        </ul>
    </div>


    <h4>@Model.CompanyName company update</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <input asp-for="CompanyId" class="form-control" />
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArabicCompanyName" class="control-label"></label>
                <input asp-for="ArabicCompanyName" class="form-control" />
                <span asp-validation-for="ArabicCompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyType" class="control-label"></label>
                <input asp-for="CompanyType" class="form-control" />
                <span asp-validation-for="CompanyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LawyerName" class="control-label"></label>
                <input asp-for="LawyerName" class="form-control" />
                <span asp-validation-for="LawyerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocsAttached" class="control-label"></label>
                <input asp-for="DocsAttached" class="form-control" />
                <span asp-validation-for="DocsAttached" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="LawyerId" /> @Html.DisplayNameFor(model => model.LawyerId)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="LawyerAuthorization" /> @Html.DisplayNameFor(model => model.LawyerAuthorization)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="FinancialAuditorName" class="control-label"></label>
                <input asp-for="FinancialAuditorName" class="form-control" />
                <span asp-validation-for="FinancialAuditorName" class="text-danger"></span>
            </div>
            <div class="checkbox">
                <label>
                    <input asp-for="FinancialAuditorApproval" /> @Html.DisplayNameFor(model => model.FinancialAuditorApproval)
                </label>
            </div>
            <div class="checkbox">
                <label>
                    <input asp-for="FinancialAuditorProfession" /> @Html.DisplayNameFor(model => model.FinancialAuditorProfession)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Address.District" class="control-label"></label>
                @Html.DropDownListFor(model => model.Address.District, (SelectList)ViewBag.Districts, new { @class = "form -control" })
                <span asp-validation-for="Address.District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Kaza" class="control-label"></label>
                @Html.DropDownListFor(model => model.Address.Kaza, (SelectList)ViewBag.Kazas, new { @class = "form -control" })
                <span asp-validation-for="Address.Kaza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Road" class="control-label"></label>
                <input asp-for="Address.Road" class="form-control" />
                <span asp-validation-for="Address.Road" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Building" class="control-label"></label>
                <input asp-for="Address.Building" class="form-control" />
                <span asp-validation-for="Address.Building" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Floor" class="control-label"></label>
                <input asp-for="Address.Floor" class="form-control" />
                <span asp-validation-for="Address.Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>

        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript">
        $(document).ready(function () {

            $(".successmessage").fadeOut(3000);

        });

    </script>

}

CDB.WebApi/Views/Companies/Index.cshtml
@model IEnumerable<CDB.BLL.Dto.Request.CompanyDto>

@{
    ViewData["Title"] = "List of companies";
}

<h4>List of companies</h4>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArabicCompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArabicCompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyType)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Companies", new { id = item.Id }) |
                @Html.ActionLink("Details", "View", "Companies", new {  id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

CDB.WebApi/Views/Companies/UpdateCompanyPaneAsync.cshtml
@using CDB.Common;

@model CDB.BLL.Dto.Request.PaneCompanyDto

@{
    ViewData["Title"] = "UpdateCompanyPaneAsync";
}

<div class="message" style="text-align:center;color:green">
    <span>@ViewBag.Message</span>
</div>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li class="disabled" style="background-color:#d9edf7"><a asp-area="" asp-controller="Companies" asp-action="UpdateCompanyPaneAsync" asp-route-id="@Model.CompanyId">Company</a></li>
        <li><a asp-area="" asp-controller="Shareholders" asp-action="Index" asp-route-id="@Model.CompanyId">Shareholders</a></li>
        <li><a asp-area="" asp-controller="Documents" asp-action="UpdateDocumentPaneAsync" asp-route-id="@Model.CompanyId">Documents</a></li>
    </ul>
</div>
<form asp-action="UpdateCompanyPaneAsync">

    <div class="panel panel-info">
        <div class="panel-heading"><b>@Constants.DISPLAY_PANEL_BASIC_INFORMATION / @Constants.DISPLAY_PANEL_BASIC_INFORMATION_AR</b></div>
        <div class="panel-body">
            @{ await Html.RenderPartialAsync("_UpdateBasicCompany", Model.Company);}
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading"><b>@Constants.DISPLAY_PANEL_COMPANY_ADDRESS / @Constants.DISPLAY_PANEL_COMPANY_ADDRESS_AR</b></div>
        <div class="panel-body">
            @{ await Html.RenderPartialAsync("_UpdateAddress", Model.Address);}
        </div>
    </div>
    @*<div class="panel panel-info">
        <div class="panel-heading"><b>@Constants.DISPLAY_PANEL_LAWYER_INFORMATION/ @Constants.DISPLAY_PANEL_LAWYER_INFORMATION_AR</b></div>
        <div class="panel-body">
            @{ await Html.RenderPartialAsync("_UpdateLawyer", Model.Lawyer);}
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading"><b>@Constants.DISPLAY_PANEL_FINANCIAL_AUDITOR_INFORMATION/@Constants.DISPLAY_PANEL_FINANCIAL_AUDITOR_INFORMATION_AR</b></div>
        <div class="panel-body">
            @{ await Html.RenderPartialAsync("_UpdateFinancialAuditor", Model.FinancialAuditor);}
        </div>
    </div>*@
   
    <div class="form-group">
        <input type="submit" value="Update" class="btn btn-default">
    </div>


</form>
<!-- YAMLI CODE START -->
<script type="text/javascript" src="https://api.yamli.com/js/yamli_api.js"></script>
<script type="text/javascript">
    if (typeof (Yamli) == "object" && Yamli.init({ uiLanguage: "en", startMode: "onOrUserDefault" })) {
        Yamli.yamlify("", { settingsPlacement: "bottomLeft" });
        Yamli.yamlify('ArabicCompanyName');
        Yamli.yamlify('FinancialAuditorName');
        Yamli.yamlify('ShareHoldersName');
        Yamli.yamlify('ShareHoldersPosition');
        Yamli.yamlify('RegistPlaceNumb');
        Yamli.yamlify('AuthorizedSignature');
        Yamli.yamlify('LawyerName');

    }
</script>
<!-- YAMLI CODE END -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CDB.WebApi/Views/Companies/UpdateShareholderPaneAsync.cshtml
@using CDB.Common;

@model CDB.BLL.Dto.Request.PaneShareholderDto

@{
    ViewData["Title"] = "UpdateShareHolderPaneAsync";
}


<form asp-action="CreateAsync">
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Companies" asp-action="UpdateCompanyPaneAsync" asp-route-id="@Model.CompanyId">Company</a></li>
            <li class="disabled" style="background-color:#d9edf7"><a asp-area="" asp-controller="Company" asp-action="UpdateShareholderPaneAsync" asp-route-id="@Model.CompanyId">Shareholders</a></li>
            <li><a asp-area="" asp-controller="Documents" asp-action="UpdateDocumentPaneAsync" asp-route-id="@Model.CompanyId">Documents</a></li>
        </ul>
    </div>


    <table class="table">
        <thead>
            <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Shareholders[0].FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Shareholders[0].PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Shareholders[0].PlaceAndDateOfBirth)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Shareholders[0].ShareContribution)
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Shareholders)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlaceAndDateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShareContribution)
                </td>
                <td>
                    @Html.ActionLink("Edit", "UpdateCompanyPaneAsync", "Companies", new { id = item.Id }) |
                    @Html.ActionLink("Details", "UpdateCompany", "Companies", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
            }
        </tbody>
    </table>


            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-default" onclick="clickAlert()" />
            </div>
            <script>
                function clickAlert() {
                    if ($("#txt-name").val() == '')
                        $("#error-label-txt-name").show()
                    else
                        $("#error-label-txt-name").hide()

                    if ($("#txt1-name").val() == '')
                        $("#error-label-txt1-name").show()
                    else
                        $("#error-label-txt1-name").hide()

                    if ($("#txt-phone").val() == '')
                        $("#error-label-txt-phone").show()
                    else
                        $("#error-label-txt-phone").hide()

                    if ($("#txt1-phone").val() == '')
                        $("#error-label-txt1-phone").show()
                    else
                        $("#error-label-txt1-phone").hide()

                    if ($("#txt-share").val() == '')
                        $("#error-label-txt-share").show()
                    else
                        $("#error-label-txt-share").hide()

                    if ($("#txt1-share").val() == '')
                        $("#error-label-txt1-share").show()
                    else
                        $("#error-label-txt1-share").hide()

                    if ($("#txt-fnumber").val() == '')
                        $("#error-label-txt-fnumber").show()
                    else
                        $("#error-label-txt-fnumber").hide()

                    if ($("#txt1-fnumber").val() == '')
                        $("#error-label-txt1-fnumber").show()
                    else
                        $("#error-label-txt1-fnumber").hide()

                    if ($("#txt-dob").val() == '')
                        $("#error-label-txt-dob").show()
                    else
                        $("#error-label-txt-dob").hide()

                    if ($("#txt1-dob").val() == '')
                        $("#error-label-txt1-dob").show()
                    else
                        $("#error-label-txt1-dob").hide()

                    if ($("#txt-nationality").val() == '')
                        $("#error-label-txt-nationality").show()
                    else
                        $("#error-label-txt-nationality").hide()

                    if ($("#txt1-nationality").val() == '')
                        $("#error-label-txt1-nationality").show()
                    else
                        $("#error-label-txt1-nationality").hide()

                    if ($("#txt-procuratorname").val() == '')
                        $("#error-label-txt-procuratorname").show()
                    else
                        $("#error-label-txt-procuratorname").hide()

                    if ($("#txt1-procuratorname").val() == '')
                        $("#error-label-txt1-procuratorname").show()
                    else
                        $("#error-label-txt1-procuratorname").hide()


                    alert("Saved Successfully!");
                    $('form :input').val('')
                }
            </script>



</form>


<!-- YAMLI CODE START -->
<script type="text/javascript" src="https://api.yamli.com/js/yamli_api.js"></script>
<script type="text/javascript">
    if (typeof (Yamli) == "object" && Yamli.init({ uiLanguage: "en", startMode: "onOrUserDefault" })) {
        Yamli.yamlify("", { settingsPlacement: "bottomLeft" });
        Yamli.yamlify('ArabicCompanyName');
        Yamli.yamlify('FinancialAuditorName');
        Yamli.yamlify('ShareHoldersName');
        Yamli.yamlify('ShareHoldersPosition');
        Yamli.yamlify('RegistPlaceNumb');
        Yamli.yamlify('AuthorizedSignature');
        Yamli.yamlify('LawyerName');

    }
</script>
<!-- YAMLI CODE END -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}